### ISSUE TITLE
Bootstrap 3.3.6 LESS Problem

### ISSUE THREAD

**Issue by erayaydin** [toopay/bootstrap-markdown#229]
Hello,

My bower.json

```
    "bootstrap": "3.3.6",
    "bootstrap-markdown": "^2.10.0"
```

LESS compiler makes error:

```
Less Compilation Failed: variable @table-border-color is undefined in file /bower_components/bootstrap-markdown/less/bootstrap-markdown.less line no. 10
```

I think bootstrap-markdown not working with bootstrap **3.3.6** version.

**Comment by toopay** [comment]
@erayaydin You need to reference bootstrap less files.

**Comment by erayaydin** [comment]
I referenced bootstrap less file but in bootstrap's variables.less  file there is no @table-border-color . I think its removed in **3.3.6**

**Comment by toopay** [comment]
@erayaydin You can use the latest `master` code for now, the fix will be included in the next release.

**Comment by erayaydin** [comment]
Thank you :+1:
